name: 'Setup Amplitude Audio SDK'
description:
  'GitHub Action that set up Amplitude Audio SDK and make it available in your
  pipelines.'
author: 'Sparky Studios'

branding:
  icon: 'package'
  color: 'red'

inputs:
  platforms:
    description: 'The list of SDK platforms to install'
    required: true
  version:
    description: 'The version of the SDK to install'
    required: true
    default: 'nightly'
  install-dir:
    description: 'The directory where to install the SDK'
    required: false
    default: './amplitude_audio'

outputs:
  path:
    description: 'The path where the SDK has been installed'

runs:
  using: node20
  main: dist/index.js
