name: 'Setup Amplitude Audio SDK'
description:
  'GitHub Action that set up Amplitude Audio SDK and make it available in your
  pipelines.'
author: 'Sparky Studios'

branding:
  icon: 'package'
  color: 'red'

inputs:
  platforms:
    description: 'The list of SDK platforms to install'
    required: true
  version:
    description: 'The version of the SDK'
    required: true
    default: 'nightly'

runs:
  using: node20
  main: dist/index.js
